### ISSUE TITLE
Contribute a patch to mysqlproto-go

### ISSUE THREAD

**Issue by kostyantyn** [XeLabs/go-mysqlstack#1]
Hey,

I see this project is mostly based on https://github.com/pubnative/mysqlproto-go. Would you wish to make a performance patch to the origin repo?

Thanks,
Kostiantyn

**Comment by BohuTANG** [comment]
Hello @kostyantyn 

Yes, go-mysqlstack protocol(and ideas) is based on mysqlproto-go(mostly) and go-sql-driver.
I hope that as you said, but go-mysqlstack with too many changes from mysqlproto-go, there is a lot of work to do.
A better way maybe go-mysqldriver based on go-mysqlstack as his protocol library?

By the way, we have push a PR(pr1, 21 days ago) but no response recevied, that we thought mysqlproto-go no longer being maintained by anybody, during this gap go-mysqlstack is built.

**Comment by kostyantyn** [comment]
I see everything is squashed under the same commit, a bit hard to understand the part that requires changes but I can help with a transition. Also, I can add you to contributors, so you'll have direct write permissions which should speed up the process.

**Comment by BohuTANG** [comment]
OK.
go-mysqlstack now only used in benchyou as a MySQL driver:
https://github.com/XeLabs/benchyou
and it works very well for me under very high pressures.

Before building go-mysqlstack, I have try mysqldriver-go and go-sql-driver, but they are all stuck in and never wakeup under high pressures(128threads write and 128threads query), I am not sure what happened.

**Comment by kostyantyn** [comment]
Hm, I never used `mysqldriver-go` in such load. In a project, I am using it, has way less load so never encountered this issue. And I built `mysqldriver-go` just for my needs.

I am more interesting to develop the protocol in a right way as a driver is smth that can be done on top. Did some research before started working on it, an initial plan was to fix `go-sql-driver` but found that it's not possible due to limitations of a `database/sql` interface.

As `go-mysqlstack` has the same idea behind as `mysqldriver-go` it would be great to work together on it rather than building 2 separate projects, especially as they are both on very early stage. 

Let me know if you see a way to contribute to `mysqlproto-go` and we will figure out permissions.
If not, it's fine, you can close the issue :)

**Comment by BohuTANG** [comment]
@kostyantyn 
Thanks.
If I had  time, I'd be glad to do it.

**Comment by kostyantyn** [comment]
ok, no problem. If you have time, let me know. I think we can also create a separate GitHub organization for that. It might also attract other contributes. It's just hard to maintain this type of project on your own.

**Comment by BohuTANG** [comment]
@kostyantyn 

'It's just hard to maintain this type of project on your own.' -- any ideas?
We separate go-mysqlstack from benchyou aims to as a common library for the maintaince.
Originally, it is a common parts for benchyou.

**Comment by kostyantyn** [comment]
I meant the more contributes are, is better. If we could merge both protocols into 1 repo it would be great, IMO.

**Comment by BohuTANG** [comment]
Sure, but there is not yet an better way to do that, IMO.

**Comment by BohuTANG** [comment]
@kostyantyn 
Found that mysqlproto-go is better than go-mysqlstack in next-read:
https://github.com/pubnative/mysqlproto-go/blob/master/stream.go#L46
The prefetch is a good idea, but it can't handle the packet larger than 16MB:
https://dev.mysql.com/doc/internals/en/sending-more-than-16mbyte.html

go-mysqlstack does it but missing the prefetch.

**Comment by BohuTANG** [comment]
@kostyantyn 
Just add io.go for prefetch:
https://github.com/XeLabs/go-mysqlstack/blob/master/packet/io.go

**Comment by BohuTANG** [comment]
@kostyantyn 
New Benchmarks are here(Adding Malloc and TotalAlloc metrics):
https://github.com/XeLabs/go-mysqlstack/blob/master/README.md

**Comment by kostyantyn** [comment]
Thanks for keeping posted. Yes, mysqlproto-go has a clear problem of memory allocation as it always creates a new slice of bytes for every packet. This is the first thing in TODO which I plan to fix

**Comment by BohuTANG** [comment]
@kostyantyn 
In order to increase commonality, I have removed the reusing-buffer, it performs as mysqlproto-go, the performance is not bad but easy for the upper layer.
