### ISSUE TITLE
License change?

### ISSUE THREAD

**Issue by fatih** [xelabs/go-mysqlstack#11]
Hi,

Thanks for this great library. I want to ask whether you have considered changing this library's license to a more permissive license so that `go-mysqlstack` can be included in other open-source projects? As an example, right now, projects using the [Apache 2.0 license are not able](https://www.apache.org/licenses/GPL-compatibility.html) to link/import `go-mysqlstack` into their projects:

> Apache 2 software can therefore be included in GPLv3 projects because the GPLv3 license accepts our software into GPLv3 works. However, GPLv3 software cannot be included in Apache projects. The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law.

I understand it's not an easy change, but if it's possible, it would be very beneficial for users that have projects that are incompatible with GPLv3.

**Comment by BohuTANG** [comment]
xelabs is very open, change to Apache 2.0 is ok to me.
Thanks for the suggestion.

**Comment by fatih** [comment]
That’s great @BohuTANG Are you ok using BDS-3 license or MIT? A lot of open source projects are using them and they work really nice. If you prefer Apache 2.0 that’s fine as well. Let me know which one you prefer. I’ll open a PR to this repo and its dependencies. Thanks a lot again for making this decision. Much appreciated

**Comment by fatih** [comment]
This can be closed now as the license has changed to BSD 3-Clause. Thanks again to @BohuTANG to be open about this change.

**Comment by hnakamur** [comment]
I think License section in README.md should be changed too.

> go-mysqlstack is released under the GPLv3. See LICENSE

**Comment by olljanat** [comment]
@fatih btw are aware of some project which is nowadays using go-mysqlstack?

**Comment by bohutang** [comment]
@olljanat 

https://github.com/radondb/radon
