### ISSUE TITLE
Is there a way to retrieve the password from server side?

### ISSUE THREAD

**Issue by kbfu** [xelabs/go-mysqlstack#15]
Hi there,
I was trying to start a mock server.
I can get the user from the session, but I was unable to get the password from it. I would like to verify the password when some one connecting the mock server.
I was not sure if I missed something. Any idea?

**Comment by bohutang** [comment]
I guess this is you want:
https://github.com/radondb/radon/blob/master/src/proxy/auth.go#L68

Check the auth in the session.

**Comment by kbfu** [comment]
> I guess this is you want: https://github.com/radondb/radon/blob/master/src/proxy/auth.go#L68
> 
> Check the auth in the session.

This is helpful. But I need to use the same password with the proxied MySQL server.
Still, thanks in advance!
