### ISSUE TITLE
能否开发一个新的sql parser

### ISSUE THREAD

**Issue by lostz** [XeLabs/go-mysqlstack#3]
因为vitess 的sql.y 只是兼容了部分的mysql 语法，能否完全根据mysql 的yacc 开发一个高性能的sql parser？

**Comment by BohuTANG** [comment]
@lostz 

1. vitess的sql.y支持已经非常好了(比如join等)，紧缺的是对DDL的解析(比如create table的元组解析)，这块我实现了一部分，但是没做完，其他的情况基本编辑下sql.y就简单搞定了
2. 基于yacc的解析性能应该都差不多，目前我还没找到更好的实现，因为这玩意太复杂了，所以就直接基于vitess sqlparser了
3. 这个也不错: https://github.com/cznic/ql 
4. lostz/sql这个还会继续开发吗？

**Comment by lostz** [comment]
我当初只是把c 翻译成了go，就是去尝试理解sql parser 代码，由于自己对于sql parser 理解不是很深刻，觉得就是一个玩具，一直是做运维的，看了你的代码后，发现要写出正在生产级别的sql parser 自己的能力差距太大了，但是我觉得用mysql 原生的 yacc 是对mysql 最好对兼容。
