### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by lexesv** [xelabs/go-mysqlstack#6]
Hello.
This mysql server without database file storage?

**Comment by BohuTANG** [comment]
go-mysqlstack is not a MySQL server as Oracle MySQL with storage engine, it's a library to talk with mysql/client with MySQL protocol.

You can play it as a proxy:
```
Client --> go-mysqlstack fake server -->Oracle MySQL
```

This is what RadonDB use, https://github.com/radondb/radon
